
	        columns: [
			     {
			     title: "Name",
				 field: "column_ip",
				 sortable: true,
	 	             css: { 
			        textAlign: 'left'
			       }
			     },
			     {
			     title: "Protocol",
				 field: "column_family",
				 sortable: true,
	 	             css: { 
			        textAlign: 'center'
			       }
			     },

			     {
			     title: "Seen Since",
				 field: "column_since",
				 sortable: true,
	 	             css: { 
			        textAlign: 'center'
 			       }
		   	     },
			     {
			     title: "Last Seen",
				 field: "column_last",
				 sortable: true,
	 	             css: { 
			        textAlign: 'center'
 			       }
		   	     },
			     {
			     title: "Query Number",
				 field: "column_traffic",
				 sortable: true,
	 	             css: { 
			        textAlign: 'center'
 			       }
		   	     }
