<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to ntop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-datatable.js"></script>
    <script src="/js/d3.v2.min.js"></script>
    <script src="/js/jquery.peity.min.js"></script>
    <script src="/js/rickshaw.min.js"></script>
    <script src="/js/pie-chart.js"></script>

    <link href="/css/pie-chart.css" rel="stylesheet">
    <link href="/css/rickshaw.min.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
    <![endif]-->



 <style type="text/css">
      body {
        padding-top: 0px;
        padding-bottom: 20px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 1024px;
      }

      /* Smaller table row padding */
      .table th, .table td {
        padding: 6px;
      }

      /* Custom container */
      .progress {
        margin-bottom: 0px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 20px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 22px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 20px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
  </head>
<body>

  <div class="container-narrow">


