<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to ntopng</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet" media="screen">
    <link href="/font-awesome/css/font-awesome.css" rel="stylesheet">
    <script src="/js/jquery.js"></script>
    <script src="/bootstrap/js/bootstrap.js"></script>
    <script src="/js/bootstrap-datatable.js"></script>
    <script charset="utf-8" src="/js/d3.v3.js"></script>
    <script src="/js/jquery.peity.js"></script>
    <script src="/js/rickshaw.js"></script>
    <script src="/js/pie-chart.js"></script>
    <script src="/js/gauge.js"></script>
    <link href="/css/flags.css" rel="stylesheet">
    <link href="/css/pie-chart.css" rel="stylesheet">
    <link href="/css/rickshaw.css" rel="stylesheet">
    <!-- http://kamisama.github.io/cal-heatmap/v2/ -->
    <script src="/js/cal-heatmap.js"></script>
    <link href="/css/cal-heatmap.css" rel="stylesheet">
    <script src="/js/springy-ntop.js"></script>
    <script src="/js/springyui-ntop.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
    <![endif]-->



 <style type="text/css">
      body {
        padding-top: 0px;
        padding-bottom: 20px;
      }

      /* Custom container */
      .container-narrow {
        margin-left: 20px;
        margin-right: 20px;
        /* max-width: 1024px; */
      }

      /* Smaller table row padding */
      .table th, .table td {
        padding: 6px;
      }

      /* Custom container */
      .progress {
        margin-bottom: 0px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 20px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 22px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 20px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }

      .table th.text-right,
      .table td.text-right {
        text-align: right;
      }

/* Fix for Google Maps and Twitter Bootstrap
      https://github.com/twbs/bootstrap/issues/1552
*/
img {
  max-width: none;
}
    </style>
  </head>
<body>

  <div class="container-narrow">


